# Generated by Django 3.0.4 on 2021-01-17 13:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('message', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Read', 'Read')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=150)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('keywords', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('school', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('fax', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, null=True)),
                ('smtpserver', models.CharField(max_length=150, null=True)),
                ('smtpemail', models.CharField(max_length=150, null=True)),
                ('smyppassword', models.CharField(max_length=150, null=True)),
                ('smtpport', models.CharField(max_length=150, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('facebook', models.CharField(max_length=150, null=True)),
                ('twitter', models.CharField(max_length=150, null=True)),
                ('instagram', models.CharField(max_length=150, null=True)),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('references', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
