# Generated by Django 3.0.4 on 2021-01-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactformmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
