# Generated by Django 3.0.4 on 2021-01-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_gelisim_kazanim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kazanim',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('True', 'Evet'), ('False', 'Hayır')], default='True', max_length=10),
        ),
    ]
