# Generated by Django 3.0.4 on 2020-12-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='title',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
