# Generated by Django 3.0.4 on 2021-01-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210117_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='kazanim',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.Images'),
        ),
    ]
