# Generated by Django 3.0.4 on 2020-12-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201212_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
