# Generated by Django 3.0.4 on 2021-01-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_kazanim_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelisim',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
