# Generated by Django 3.0.4 on 2021-01-07 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='gostergeler',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=250),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
