# Generated by Django 3.0.4 on 2021-01-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210117_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='kavram',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='images',
            name='surec',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
