# Generated by Django 3.0.4 on 2021-01-07 20:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210107_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='gostergeler',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=250),
        ),
    ]
