# Generated by Django 3.0.4 on 2021-01-17 15:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210117_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='kavram',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='surec',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
