# Generated by Django 3.0.4 on 2021-01-17 15:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210117_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
