# Generated by Django 3.0.4 on 2021-01-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210107_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='detail',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
