# Generated by Django 3.0.4 on 2021-01-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210107_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='detail',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
