# Generated by Django 3.0.4 on 2021-01-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20210107_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='gostergeler',
        ),
    ]
