# Generated by Django 3.0.4 on 2021-01-07 21:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_images_gostergeler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='gostergeler',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5, null=True), blank=True, null=True, size=None),
        ),
    ]
